app = "Vaultwarden0222"  # 应用名称
primary_region = "ord"  # 数据中心，比如 hkg、nrt、sin

[build]
  image = "eooce/nodejs:latest"  # 镜像地址

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
 cpus = 1
 memory = "256mb"
 memory_mb = 256
